spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/querydsl
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true